# see https://github.com/compose-spec/compose-spec
# see https://docs.docker.com/compose/overview/
# see https://docs.docker.com/compose/compose-file/
services:
  hello:
    build: hello
    ports:
      - "8888"
    depends_on:
      - etcd
    restart: on-failure
  etcd:
    build: etcd
    restart: on-failure
