# see https://github.com/compose-spec/compose-spec
# see https://docs.docker.com/compose/overview/
# see https://docs.docker.com/compose/compose-file/
services:
  hello:
    build: hello
    ports:
      # NB since this port is declared as a single integer, docker compose will
      #    automatically allocate a port in the host. to later known the
      #    allocated port use docker compose port hello 8888
      - "8888"
    depends_on:
      etcd:
        condition: service_healthy
    restart: on-failure
    labels:
      # NB you can see these container labels with docker inspect.
      com.example: example
  etcd:
    build: etcd
    command:
      - --name=etcd
      - --data-dir=c:/etcd-data
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health", "--dial-timeout=2s", "--command-timeout=3s"]
      start_period: 5s
      interval: 15s
      timeout: 5s
      retries: 2
    restart: on-failure
    volumes:
      - etcd-data:c:/etcd-data
volumes:
  etcd-data:
