# see https://docs.docker.com/compose/overview/
# see https://docs.docker.com/compose/compose-file/
version: '3.7'
services:
  hello:
    build: hello
    ports:
      - "5000:8888"
    depends_on:
      - etcd
    restart: on-failure
  etcd:
    build: etcd
    restart: on-failure
